version: '3.2'
services:
  weaviate:
    build:
      context: .
      args:
        - config
        - action_schema
        - thing_schmea
  db:
    image: cassandra:3
    volumes: 
      - ~/cassandra:/var/lib/cassandra
    ports: 
      - 7000:7000
      - 9042:9042
    environment: 
      CASSANDRA_BROADCAST_ADDRESS: 127.0.0.1
      CASSANDRA_START_RPC: "true"
